<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-29 16:39
=======
# Generated by Django 4.1.2 on 2022-10-29 04:10
>>>>>>> 387711572570be5cf93b09355e159e3c63a40a34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
